name: Run Clippy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo clippy
